"""
Record and replay.

A recorded run is a directory under runs/ containing everything needed to play
the demo back with the network cable out:

    runs/<run_id>/
        meta.json      seed, prior, provider, timestamps, versions
        events.jsonl   one JSON object per streamed message, in order
        metrics.json   the final metrics + readiness block
        bandit.json    the final bandit state (A, b, pulls per arm)

Note on what is in `events.jsonl`: the rendered frames it contains are *renders
of the SceneGraph*, generated by the provider. They are not the user's camera
frames — those were discarded at perception and never reach this module.
"""
from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

RUNS_DIR = Path(os.getenv("SKOPOS_RUNS_DIR", "runs"))


def _run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S", time.localtime())


class Recorder:
    def __init__(self, run_id: Optional[str] = None) -> None:
        self.run_id = run_id or _run_id()
        self.dir = RUNS_DIR / self.run_id
        self.dir.mkdir(parents=True, exist_ok=True)
        self._events = (self.dir / "events.jsonl").open("w", encoding="utf-8")
        self.count = 0
        self.started = time.time()

    def write_meta(self, meta: Dict[str, Any]) -> None:
        meta = dict(meta)
        meta["run_id"] = self.run_id
        meta["started_at"] = self.started
        (self.dir / "meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    def event(self, msg: Dict[str, Any]) -> None:
        self._events.write(json.dumps(msg, separators=(",", ":")) + "\n")
        self.count += 1

    def close(self, metrics: Dict[str, Any], bandit: Dict[str, Any]) -> Dict[str, Any]:
        self._events.close()
        (self.dir / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
        (self.dir / "bandit.json").write_text(json.dumps(bandit, indent=2), encoding="utf-8")
        return {
            "run_id": self.run_id,
            "path": str(self.dir.resolve()),
            "events": self.count,
            "seconds": round(time.time() - self.started, 2),
        }


def list_runs() -> List[Dict[str, Any]]:
    if not RUNS_DIR.exists():
        return []
    out = []
    for d in sorted(RUNS_DIR.iterdir(), reverse=True):
        if not d.is_dir() or not (d / "events.jsonl").exists():
            continue
        meta = {}
        mp = d / "meta.json"
        if mp.exists():
            try:
                meta = json.loads(mp.read_text(encoding="utf-8"))
            except Exception:
                meta = {}
        lines = sum(1 for _ in (d / "events.jsonl").open(encoding="utf-8"))
        out.append({
            "run_id": d.name,
            "events": lines,
            "seed": meta.get("seed"),
            "provider": meta.get("provider"),
            "started_at": meta.get("started_at"),
        })
    return out


def replay_events(run_id: str) -> Iterator[Dict[str, Any]]:
    """Yield a recorded run's events in order. Touches nothing but the disk."""
    path = RUNS_DIR / run_id / "events.jsonl"
    if not path.exists():
        raise FileNotFoundError("no such run: " + run_id)
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                yield json.loads(line)
